### ISSUE TITLE
Audio tags not cleaned up in player, leading to player crashing with 6+ audio elements even in a sequence

### ISSUE THREAD

**Issue by samdoeswork** [remotion-dev/remotion#1130] opened 2022-07-17 19:58 UTC
Hi,
When adding multiple audio tags in the player, there's significant limitations:

a. When the player-head is moved back to the start, all audio clips will immediately play over the top of each-other
b. When more than 6 audio tags are used it causes an error (your settings only allow 5 audio clips to me mounted at once)
c. You need to interact with the player explicitly before audio can play (this is a browser limitation. I doubt you can fix this but would be good to document it)

I think the fix is conceptually simple: keep track of all the audio tags the player has mounted, and check on each render whether they should still exist, then remove the audio tag from the DOM.

If this causes an issue with pre-loading or something, then you could add a new property: mountedBetweenFrames .

I've tried every method I could think of and all get this behaviour.

**Comment by JonnyBurger** [comment] 2022-07-18 07:13
Hi @samdoeswork!

a.) Could it be that you have Strict mode enabled? This is indeed a bug with us, see here: https://www.remotion.dev/docs/player/autoplay#use-the-numberofsharedaudiotags-property
Issue to track: https://github.com/remotion-dev/remotion/issues/723

The workaround at the moment is to disable strict mode, but that is high on my priority list!

b.) You may customize that number to be as high as possible or disable our autoplay helper completely: https://www.remotion.dev/docs/player/autoplay

c.) Correct, the user needs to trigger audio playback using a click event, and it is also documented under the above URL. The premounting of audio tags can actually help you so you only need to start the Remotion video once via user event and then all audio may play regardless of the location in the video.

I think you did not find the autoplay doc, I recommend reading it to learn about how to deal with autoplay as well as possible!
If you are not in strict mode, let me know and I can investigate it further!

**Comment by samdoeswork** [comment] 2022-07-18 10:08
@JonnyBurger  thanks. I hadn't seen that, sorry. (I did look & search all around player and audio, but didn't realize it was documented under AutoPlay).

For my use case (a lot of audio elements mostly in-sequence) the shared-audio-tags seems to cause issues. Opting out by setting them to 0 helps - thank you.

I think for my specific use-case setting the number of SharedAudioTags={0} and doing audio preload tags myself is likely the best strategy.

**Comment by JonnyBurger** [comment] 2022-07-18 13:11
@samdoeswork Alright!

Do you have strict mode enabled in your app?
I'd like to know whether this issue can be considered a duplicate of #273.

**Closed** 2022-07-23 10:33 UTC
Labels: bug
