### ISSUE TITLE
Could not extract frame from compositor Error: connect ECONNREFUSED ::1:3000

### ISSUE THREAD

**Issue by AmitDJagtap** [remotion-dev/remotion#4329] opened 2024-09-26 13:13 UTC
I am using SSR to render a composition and  facing this issue. I am using node v18.20.0 and following packages. 

OS - Windows 
Node - v18.20.0 | NPM - 10.5.2
Remotion - 4.0.212

Similar issue : https://github.com/remotion-dev/remotion/issues/3471

```
    "@remotion/bundler": "4.0.212",
    "@remotion/renderer": "4.0.212",
```
---
render.mjs
```
import { bundle } from '@remotion/bundler';
import { renderMedia, selectComposition } from '@remotion/renderer';
import path from 'path';

// The composition you want to render
const compositionId = 'VideosConcat';

// You only have to create a bundle once, and you may reuse it
// for multiple renders that you can parametrize using input props.
const bundleLocation = await bundle({
    entryPoint: path.resolve('./autoeditor/src/index.ts'),
    rootDir:path.resolve('./autoeditor') ,
    webpackOverride: (config) => config,
});


const inputProps = {
    clips: [{ url: "v1.mp4" }, { url: "v2.mp4" }, { url: "v3.mp4" }],
    fit: 'cover',
    backgroundMusic: { url: "ncs_X.mp3", isVideo: false }
};
```
---
Folder Structure
```
myNodeApp
 '- app
  '-- render.js
 '- remotion
     '-- src
     '-- public
     '-- package.json
  '-- otherService
  '-- package.json
```
---
Error

```
>> node .\app\render.mjs
 renderMedia()  Free memory: 6269808640 Estimated usage parallel encoding 2073600000
 renderMedia()  Using concurrency: 6
 renderMedia()  delayRender() timeout: 30000
 renderMedia()  Codec supports parallel rendering: true
 renderMedia()  Parallel encoding is enabled.
 renderMedia()  Rendering frames 0-4499
 prespawnFfmpeg()  Generated FFMPEG command:
 prespawnFfmpeg()  -r,60 -f,image2pipe -s,1920x1080 -vcodec,mjpeg -i,- -c:v,libx264 -pix_fmt,yuv420p -crf,18 -y C:\Users\damitj\AppData\Local\Temp\react-motion-renderodjJXQ\pre-encode.mp4
Created directory for temporary files C:\Users\damitj\AppData\Local\Temp\remotion-v4-0-213-assetsxnbqu6qd7f
 openBrowser()  Opening browser: gl = undefined, executable = C:\Users\damitj\go\src\hub2\node_modules\.remotion\chrome-headless-shell\win64\chrome-headless-shell-win64\chrome-headless-shell.exe, enableMultiProcessOnLinux = true
 compositor  Starting Rust process. Max video cache size: 2441MB, max concurrency = 6
 node_modules/@remotion/media-utils/dist/get-audio-data.js:37  
 chrome  [0926/184214.595:INFO:CONSOLE(485)] "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu", source: http://localhost:3000/bundle.js (485)
 node_modules/@remotion/media-utils/dist/get-audio-data.js:37  
 chrome  [0926/184214.602:INFO:CONSOLE(485)] "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu", source: http://localhost:3000/bundle.js (485)
 node_modules/@remotion/media-utils/dist/get-audio-data.js:37  
 chrome  [0926/184214.610:INFO:CONSOLE(485)] "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu", source: http://localhost:3000/bundle.js (485)
 node_modules/@remotion/media-utils/dist/get-audio-data.js:37  
 chrome  [0926/184214.618:INFO:CONSOLE(485)] "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu", source: http://localhost:3000/bundle.js (485)
 node_modules/@remotion/media-utils/dist/get-audio-data.js:37  
 chrome  [0926/184214.624:INFO:CONSOLE(485)] "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu", source: http://localhost:3000/bundle.js (485)
 node_modules/@remotion/media-utils/dist/get-audio-data.js:37  
 chrome  [0926/184214.631:INFO:CONSOLE(485)] "The AudioContext was not allowed to start. It must be resumed (or created) after a user gesture on the page. https://goo.gl/7K7WLu", source: http://localhost:3000/bundle.js (485)
Could not extract frame from compositor Error: connect ECONNREFUSED ::1:3000
 http://localhost:3000/proxy?src=http%3A%2F%2Flocalhost%3A3000%2Fpublic%2Fwarhammer1.mp4&time=0&transparent=false&toneMapped=true  Failed to load resource: the server responded with a status of 500 (Internal Server Error)
 chrome  [0926/184216.274:INFO:CONSOLE(8653)] "Uncaught (in promise) Error: connect ECONNREFUSED ::1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)", source: http://localhost:3000/bundle.js (8653)
node:internal/process/esm_loader:40
      internalBinding('errors').triggerUncaughtException(
                                ^

Error: connect ECONNREFUSED ::1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1555:16)
    at execute (http://localhost:3000/bundle.js:8653:35) {
  stackFrame: [
    {
      columnNumber: 16,
      fileName: 'node:net',
      functionName: 'TCPConnectWrap.afterConnect [as oncomplete]',
      lineNumber: 1555
    },
    {
      columnNumber: 35,
      fileName: 'http://localhost:3000/bundle.js',
      functionName: 'execute',
      lineNumber: 8653
    }
  ],
  frame: null,
  chunk: null,
  name: 'CancelledError',
  delayRenderCall: null
}

Node.js v18.20.0
```
I tried NPM update and cache verify as well, ensuring remotion & render,budler version are same.

**Comment by AmitDJagtap** [comment] 2024-09-26 13:23
I also checked by if the assets are getting copied in bundle/public. by seetting the bundel output dir.

const bundleLocation = await bundle({
    entryPoint: path.resolve('./autoeditor/src/index.ts'),
    rootDir:path.resolve('./autoeditor') ,
    outDir : path.resolve('./autoeditor/dist'), // here
    webpackOverride: (config) => config,
});

**Comment by AmitDJagtap** [comment] 2024-09-26 13:34
Seems also an issue with the Hello World template. Steps to reptoruce 

- npx create-video@latest
- select hello worlds
- creat public dir in root 
- Add ur video
- create a video element in any compsotion
- run < npm run build>

```

> testpub@1.0.0 build
> remotion render HelloWorld out/video.mp4

Bundled code         ━━━━━━━━━━━━━━━━━━ 1006ms
Composition          HelloWorld
Codec                h264
Output               out/video.mp4
Concurrency          6x
Rendering frames     ━━━━━━━━━━━━━╸━━━━ 115/150 4s remaining
Downloading assets   0 B                 1 file       
↓ 0 B      http://localhost:3000/public/warhammer1.mp4
Encoding video       ━━━━━━━━━━━━━━━━━━   0/150Could not extract frame from compositor Error: connect ECONNREFUSED ::1:3000
 http://localhost:3000/proxy?src=http%3A%2F%2Flocalhost%3A3000%2Fpublic%2Fwarhammer1.mp4&time=0&transparent=false&toneMapped=true  Failed to load resource: the server responded with a status of 500 (Internal Server Error)
node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: write EOF
    at WriteWrap.onWriteComplete [as oncomplete] (node:internal/stream_base_commons:94:16) {
  errno: -4095,
  code: 'EOF',
  syscall: 'write'
}

Node.js v18.20.0
```

**Comment by JonnyBurger** [comment] 2024-09-27 07:47
Thanks for filing - are you using WSL?
If yes, which distro?

**Comment by drakejin** [comment] 2024-09-27 08:13
I am using Remotion rendering on AWS Lambda.

Although I cannot say this is the exact same issue, it is a similar phenomenon, so I am writing about it here.

Below is the CloudWatch log of a Lambda render:

“Failed to fetch http://localhost:3000/proxy?src=https%3A%2F%2Fvideos.pexels.com%2Fvideo-files%2F8041859%2F8041859-uhd_1440_2732_25fps.mp4&time=0&transparent=false&toneMapped=true. This could be caused by Chrome rejecting the request because the disk space is low. Consider increasing the disk size of your environment.”

**Comment by JonnyBurger** [comment] 2024-09-27 08:30
@drakejin Yes, this is a different issue.
I think your issue can be resolved by setting the disk size to 10GB! (This will increase the cost by less than 1%)

**Comment by drakejin** [comment] 2024-09-27 08:58
@JonnyBurger 
Wow, I’m really amazed. Thanks It resolved!

Actually, before raising this issue, I was investigating how to increase the disk size of the Chrome headless browser in Lambda. I was also in the process of reproducing the error by referring to the Next.js page directory example from the official Remotion GitHub, just to raise the issue.

As soon as I saw your response, I followed your guidance immediately, and I confirmed that the issue was resolved.

Thank you very much!

**Comment by AmitDJagtap** [comment] 2024-09-29 07:28
I am not using WSL. I have Windows 10 Version 22H2 for x64-based Systems (KB5043131).
  IDE - VSCode
  ffmpeg version 7.0.2-essentials_buil

**Comment by JonnyBurger** [comment] 2024-10-11 07:30
@AmitDJagtap Please follow #4315, it seems to be the same issue

**Closed** 2024-10-11 07:30 UTC
Labels: bug

**Comment by AmitDJagtap** [comment] 2024-10-12 08:39
Hey @JonnyBurger I couldn't really get what the resolution was from #4315
