### ISSUE TITLE
ThreeCanvas sizing bug on high dpr displays

### ISSUE THREAD

**Issue by keisans** [remotion-dev/remotion#2577] opened 2023-07-12 18:43 UTC
# Bug Report 🐛

There looks to be an issue with the size of the React Three Fiber canvas and the size of the remotion video area on displays with higher pixel ratios

| Expected  | Actual |
| ------------- | ------------- |
|  <img width="800" alt="Screenshot 2023-07-12 at 2 31 15 PM" src="https://github.com/remotion-dev/remotion/assets/627906/8bf54db0-ef99-4265-9a1b-3d168b41c2d6"> |  <img width="803" alt="Screenshot 2023-07-12 at 2 30 28 PM" src="https://github.com/remotion-dev/remotion/assets/627906/92de7859-2ecf-43d7-bfd4-f887d4c71b84"> |

This only occurs when using my laptop screen (MBP 14" / dpr = 2) and does not happen on my external monitor (Asus 24" / dpr = 1).

My best guess so far is that there might be an issue with the way that the `<Scale>` component is resizing the canvas in `<ThreeCanvas>` when dealing with a high dpr environment, but there could be other pieces I'm missing. I am able to get the desired output by explicitly setting the html `<canvas>` style width in the inspector, but I haven't found a clean way to handle that in React and I would expect `<ThreeCanvas>` to handle that detail automatically.

**Comment by JonnyBurger** [comment] 2023-07-13 07:50
Thanks for reporting - we've seen your issue and acknowledge it!
Given an increase in issues and requests, it will take a few days for us to investigate and respond to it - thanks for your patience.

**Comment by patsalv** [comment] 2023-08-07 09:55
@keisans 
I investigated it but could not reproduce this behavior. Could you maybe provide the example component wich shows the unecpected behavior?

**Comment by JonnyBurger** [comment] 2023-08-27 10:35
We've looked at the issue in the team, but with our monitors and our test Three scenes, we could not reproduce the issue. Due to no repro provided, we need to close the issue unfortunately.

**Closed by JonnyBurger** 2023-08-27 10:35 UTC
Labels: bug
