### ISSUE TITLE
Error when preview the example scene

### ISSUE THREAD

**Issue by woshichuanqilz** [remotion-dev/remotion#920] opened 2022-04-10 07:40 UTC
My situation: 
```
 OS: Manjaro 21.2.5 Qonos
 Kernel: x86_64 Linux 5.15.28-1-MANJARO
 Uptime: 25m
 Packages: 1612
 Shell: python
 Resolution: 1920x1080
 DE: KDE 5.91.0 / Plasma 5.24.3
 WM: KWin
 GTK Theme: Breeze [GTK2/3]
 Icon Theme: breeze
 Disk: 73G / 236G (33%)
 CPU: Intel Core i7-7700K @ 8x 4.5GHz [44.0°C]
 GPU: Mesa Intel(R) HD Graphics 630 (KBL GT2)
 RAM: 6030MiB / 15866MiB

node -v
v17.7.1

npm -v
8.5.4
```

I follow the instructions here: https://www.remotion.dev/docs/#installation

After that I get a "my-video" folder. Then I check the `Preview your video` by command `npm start` but get error. 

* The output of my `npm config get ignore-scripts` is `false`.
How to solve my problem?

```
~/R/my-video (main|✔) $ npm start                                                                                                        15:24:13
> my-video@1.0.0 start
> remotion preview src/index.tsx

/home/lizhe/RemotionProject/my-video/node_modules/esbuild/bin/esbuild:2
throw new Error(`esbuild: Failed to install correctly
^

Error: esbuild: Failed to install correctly

Make sure you don't have "ignore-scripts" set to true. You can check this with
"npm config get ignore-scripts". If that returns true you can reset it back to
false using "npm config set ignore-scripts false" and then reinstall esbuild.

If you're using npm v7, make sure your package-lock.json file contains either
"lockfileVersion": 1 or the code "hasInstallScript": true. If it doesn't have
either of those, then it is likely the case that a known bug in npm v7 has
corrupted your package-lock.json file. Regenerating your package-lock.json file
should fix this issue.

 at Object.<anonymous> (/home/lizhe/RemotionProject/my-video/node_modules/esbuild/bin/esbuild:2:7)
 at Module._compile (node:internal/modules/cjs/loader:1099:14)
 at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
 at Module.load (node:internal/modules/cjs/loader:975:32)
 at Function.Module._load (node:internal/modules/cjs/loader:822:12)
 at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
 at node:internal/main/run_main_module:17:47

Node.js v17.7.1
webpack built 6d68c1e8d4ed3329 in 552ms
asset bundle.js 1.92 MiB [emitted] (name: main) 1 related asset
cached modules 1.69 MiB (javascript) 28.8 KiB (runtime) [cached] 364 modules
orphan modules 1.84 KiB [orphan] 2 modules
./src/index.tsx 39 bytes [built] [1 error]

ERROR in ./src/index.tsx
Module build failed (from ./node_modules/esbuild-loader/dist/index.js):
Error: The service was stopped
 at /home/lizhe/RemotionProject/my-video/node_modules/esbuild/lib/main.js:1258:29
 at /home/lizhe/RemotionProject/my-video/node_modules/esbuild/lib/main.js:611:9
 at Socket.afterClose (/home/lizhe/RemotionProject/my-video/node_modules/esbuild/lib/main.js:589:7)
 at Socket.emit (node:events:539:35)
 at endReadableNT (node:internal/streams/readable:1342:12)
 at processTicksAndRejections (node:internal/process/task_queues:83:21)

webpack 5.60.0 compiled with 1 error in 552 ms
webpack built 6d68c1e8d4ed3329 in 552ms
Error: Not allowed to open Socket.afterClose
 at getFileSource (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/dist/error-overlay/react-overlay/utils/get-file-source.js:12:15)
 at /home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/dist/start-server.js:70:45
 at Layer.handle [as handle_request] (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/layer.js:95:5)
 at next (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/route.js:137:13)
 at Route.dispatch (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/route.js:112:3)
 at Layer.handle [as handle_request] (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/layer.js:95:5)
 at /home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:281:22
 at Function.process_params (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:335:12)
 at next (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:275:10)
 at middleware (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/dist/hot-middleware/index.js:45:20)
 at Layer.handle [as handle_request] (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:317:13)
 at /home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:335:12)
 at next (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:275:10)
 at goNext (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/dist/dev-middleware/middleware.js:40:20)
 at processRequest (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/dist/dev-middleware/middleware.js:46:23)
 at ready (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/dist/dev-middleware/ready.js:6:9)
 at /home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/dist/dev-middleware/middleware.js:38:27
 at Layer.handle [as handle_request] (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:317:13)
 at /home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:335:12)
 at next (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:275:10)
 at expressInit (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/middleware/init.js:40:5)
 at Layer.handle [as handle_request] (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:317:13)
 at /home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:335:12)
 at next (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:275:10)
 at query (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/middleware/query.js:45:5)
 at Layer.handle [as handle_request] (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/layer.js:95:5)
 at trim_prefix (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:317:13)
 at /home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:284:7
 at Function.process_params (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:335:12)
 at next (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:275:10)
 at Function.handle (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/router/index.js:174:3)
 at Function.handle (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/application.js:174:10)
 at Server.app (/home/lizhe/RemotionProject/my-video/node_modules/@remotion/bundler/node_modules/express/lib/express.js:39:9)
 at Server.emit (node:events:527:28)
 at parserOnIncoming (node:_http_server:955:12)
 at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
^C⏎
```

**Comment by JonnyBurger** [comment] 2022-04-10 13:09
Hi @woshichuanqilz!

Thanks for reporting. I tried to reproduce it myself on Ubuntu with Node17/NPM 8 and while this configuration worked for me, I suspect that on other Linux distros the `esbuild` package is less tested.

I am hopeful that the issue will be fixed in our V3 version which will be released this month, since we removed the esbuild-loader and upgrade to a newer version of ESBuild, that seems to have removed this error message, indicating that a proper fix has landed.

Since we are so close to releasing V3, I am going to not investigate further. If you like, you can try to replace all Remotion packages in package.json in the package.json with `3.0.0-lambda.439+8583491c7`: https://www.remotion.dev/docs/prereleases?version=3.0.0-lambda.439%2B8583491c7

**Closed** 2022-04-24 19:07 UTC
Labels: bug
