### ISSUE TITLE
Dynamically set `width` and `height` & FPS

### ISSUE THREAD

**Issue by tomByrer** [remotion-dev/remotion#808] opened 2022-01-31 01:45 UTC
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%24167%20Rewarded-%237E24E3.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/808)

_Edit by @JonnyBurger:_

**🎃 This issue is part of our Hacktoberfest campaign!**
📚 [Read more about Hacktoberfest here](https://remotion.dev/hacktoberfest)
✅ This issue is currently assigned to @exitflynn!

## Hacktoberfest acceptance criteria:

- Should introduce new `height` and `width` flags for `renderMediaOnLambda()` and `renderStillOnLambda()` (it is not required for `renderMedia()` and `renderStill()` since you can override the `composition` object)
- Should introduce a new `--height` and `--width` flag to be used for the `npx remotion render`, `npx remotion still`, `npx remotion lambda render` and `npx remotion lambda still` commands.
- These flags will override the width and height of the render regardless of what was passed to `<Composition>`.
- Some restrictions apply: For h264 videos, the dimensions must be even (divisible by 2), must be integer and not negative. This is currently validated and one should not be able to bypass that validation
- Document the feature in all API pages where those options can be passed

---

_Original issue:_

# Use Case

Rapidly changing FPS & video size for:

* local development vs final product
* multiple [hosting target sizers](https://jacob-le.com/social-media-image-and-video-sizes/) (eg Social media)
* dynamic <Player> playback (Responsive, keep in sync with imbedded video)
* Changing FPS when source data is in seconds (eg [WebVTT](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API))

# Problem

While it is clear Remotion uses Frames and FramesPerSecond for time, & pixels for size, these are inconvenient standards for dynamic situations.  For example, the movie producer, SEO professional, etc who wants to change the video size & rate easily can not when the components hard-coded.

While everyone could hard-code their own way of handling translations, it would hinder sharing components & complicate development.

## Possible Solutions

Unsure best way forward; here is a brainstorm of easiest to complex implementation:

* Document better, with more examples of dynamic sizes/FPS
* Standardized helper functions, eg `secondsToFrames()`, `viewhightToPixels()` (I'm about to try this)
* Remotion bakes in automatic conversions similar to CSS units (`interpolate(frame, [0, 2sec], [15vw, 50vw])`)

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $167.00)

- [<img src='https://avatars.githubusercontent.com/u/1629785?v=4' alt='jonnyburger' width=24 height=24> jonnyburger](https://issuehunt.io/u/jonnyburger) ($112.00)
- [<img src='https://avatars.githubusercontent.com/u/85344006?v=4' alt='remotion-dev' width=24 height=24> remotion-dev](https://issuehunt.io/u/remotion-dev) ($55.00)

### Submitted pull Requests
- [#1427 add --height --width flags](https://issuehunt.io/r/remotion-dev/remotion/pull/1427)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by JonnyBurger** [comment] 2022-01-31 09:35
I'll break the issue down into it's parts:

- Dynamically changing the dimensions of the video at render time is something we are exploring to support. It already works with the Node.JS APIs, but it would be cool to do it via the CLI as well.

_Note: For now, you can create two compositions with the same component but different dimensions. If you want to create a responsive video, this is cool, because you can preview both styles._ 

- A hook called `useCurrentTime()` was [already proposed](https://github.com/remotion-dev/remotion/issues/609#issuecomment-937714504) to return the time in seconds, but I decided against it. Essentially, I want one standard that is used across all tutorials and libraries that are build on top of Remotion. We can more easily share code with each other and no conversion is needed when integrating libraries. The good news is that if you need it, you can trivially implement it yourself.

- Already explored support for `vh` and `vw` but it also has big drawbacks: https://github.com/remotion-dev/remotion/issues/547

- For interpolate to support seconds, it would have to plug into React context to get the `fps` value. So we'd have to make it a hook `useInterpolate` and it has to obey by the rules of hooks. It would be less versatile that it is now and require a migration.

**Comment by tomByrer** [comment] 2022-02-01 00:34
> create two compositions with the same component but different dimensions

I'm trying to avoid this, but sometimes might be needed, eg if the aspect ratio changes radically between YouTube & FaceBook/Instagram/TickTok.

The other suggestions are good, but I might have different ideas, so I guess I'll have to build demos.

**Comment by tomByrer** [comment] 2022-02-01 02:53
I changed the title due to one of my use cases, which is actually **my** primary concerns:

> * dynamic  playback (Responsive, keep in sync with imbedded video)
> * Changing FPS when source data is in seconds (eg WebVTT)

But I failed in being too vague.  My main use for Remotion is to use it along with typical videos (eg from YouTube, Vimo, etc):

* transcript/captions player, either as overlay on top of video, or outside the video.
* dynamic web pages, which will have to also be responsive

I do have use cases for _rendering_ to different social media platforms, but that is _not_ my main worry.

**Comment by tomByrer** [comment] 2022-02-03 07:11
Past my bedtime so sorry for being terse, but here is a demo I've worked on: https://github.com/tomByrer/remotion-demo-compose

Quick code examples:
```jsx
// id, width, height are calculated
// fps default is 30
//TODO: send total time from <Series> to parent <Composition>
<Helper.AdvancedComposition
  component={AboutRemotion}
  durationInSeconds={14}
  resolution='story'
/>
```

```js
/* useConvert.js */
import {useVideoConfig} from 'remotion'

export function seconds(sec){
	const videoConfig = useVideoConfig()
	return sec * videoConfig.fps
}

export function vh(h){
	const videoConfig = useVideoConfig()
	return h * videoConfig.height * 0.01
}

export function vw(w){
	const videoConfig = useVideoConfig()
	return w * videoConfig.width * 0.01
}
...
```
```js
/* useAnimation.js */
import {interpolate, spring, useCurrentFrame, useVideoConfig} from 'remotion'
import * as useConvert from '../helpers/useConvert';

export function fadeIn(seconds=0.5){
	const frame = useCurrentFrame()
	return interpolate(
		frame,
 // frames conversions makes changing FPS instant
// & seconds are easier to wrap mind around
		[0, useConvert.seconds(seconds)],
		[0, 1]
	)
}
...
```
```js
/* 
/* SomeComponant.jsx */
import * as useConvert from '../helpers/useConvert';
// although the viewport ratios are hard to read, they are responsive
<div style={{
	fontSize: useConvert.vw(3.7234),
	bottom: useConvert.vh(12.9629),
	opacity: useAnimation.useFadeIn(),
}}
>test div</div>
```

**Comment by exitflynn** [comment] 2022-10-15 20:14
Hi @JonnyBurger I'd love to take up this issue!

**Comment by JonnyBurger** [comment] 2022-10-16 09:54
@exitflynn Assigned! Good luck!

**Comment by exitflynn** [comment] 2022-10-20 15:37
hello there! :wave: 
i must admit that i was very much a newbie when it came to React and contributing to Open-Source in general when I took this issue up. I had seen the fireship video on Remotion and found the idea to be really neat. While I wanted to start contributing to open-source this hacktoberfest, I decided to search my history for nice repo's I had saved for later, remotion came up and with the added motivation of the issuehunt and the hacktoberfest tags, this issue seemed doable for me. I have been building my React knowledge since then and finally recently managed to start making some progress :cowboy_hat_face: :partying_face: (while managing my college and some volunteering work on the side).
I'm not sure why but i just felt like letting you know, this is my first time contributing to a repo in a way that is _not_ non-code :sweat_smile:

**Comment by exitflynn** [comment] 2022-10-20 15:45
I wanted to clarify which option would be more suitable, putting the `setHeight` and `getHeight` under Rendering or under the Output configType? [(for reference)](https://github.com/remotion-dev/remotion/blob/main/packages/cli/src/config/index.ts)

**Comment by JonnyBurger** [comment] 2022-10-20 17:19
@exitflynn That's awesome to hear! Love to hear a story of someone getting successfully started!

Both seems okay, if uncertain, you can put it in Config.Output!

**Comment by exitflynn** [comment] 2022-10-21 10:09
Thank you soo much for that response!
 
Apologies but major beginner question ahead, I am having trouble being able to figure out how to access the hardcoded values like the height and width of the video which the user would have specified. I am currently thinking that they'd be the ones in internals and could be accessed like so:

```import {Internals} from 'remotion';
const video = Internals.useVideo();
const height = video.height;
```

But since I am to work with the lambda cli functions, an inner voice inside me felt a little uneasy that I am not even touching the lambda directory. I am unable to figure out if the changes made in `cli/` carry over to `lambda/` cli commands, with just the added lambda prefix or is some sort of bridging or rewriting is necessary, I'm really sorry if the question is too abstract and/or broad and would really appreciate _any_ feedback.

**Comment by JonnyBurger** [comment] 2022-10-21 11:17
@exitflynn Sure!

Using useVideo() you only access the height and width once they have been set. The scope of the issue is to define the height and width explicitly before they even reach useVideo().

Check out this location in the codebase: https://github.com/remotion-dev/remotion/blob/main/packages/cli/src/render.tsx#L187

In the `config` variable, we have various metadata such as `width`, `height` and `fps`. They get pulled from your React code - here it would be great as a first step to, if someone passes `--width` or `--height` in the command line, ignore those values and overwrite the config object! Check out the `parse-command-line.ts` file as well and the variable `parsedCli` that it exposes.

That is actually already a significant part of the functionality, the other part is to just port it to also to the `still` and `lambda` commands and to then update the documentation!

**Comment by exitflynn** [comment] 2022-10-21 18:58
hey jonny! Thanks again for the response. So, I came up with that ^,  and just wanted to make sure if this works just in case there's something here that I'm fundamentally missing.

**Comment by JonnyBurger** [comment] 2022-10-28 15:11
Fixed by #1427

**Closed by JonnyBurger** 2022-10-28 15:11 UTC
Labels: :gift: Rewarded on Issuehunt, 🥨  hacktoberfest

**Comment by ammar-bay** [comment] 2023-10-04 15:27
@JonnyBurger Hey man, I just wanted to ask how can I dynamically set height in `renderMedia()`  @tomByrer said above that you can override the composition object, how can I do that?

**Comment by leonmak** [comment] 2023-12-25 08:36
@ammar-bay renderMediaOnLambda has
```
forceHeight: body.height,
forceWidth: body.width,
```
