### ISSUE TITLE
Line between shadow and element background shows on the preview

### ISSUE THREAD

**Issue by pierreminiggio** [remotion-dev/remotion#446] opened 2021-06-12 22:52 UTC
Reproduced in versions 2.1.7 & in 2.1.9 :

A "gap" between the background and the box-shadow is present on the preview (it shoudn't be), and absent from the render (as it should be).

Preview : 
![image](https://user-images.githubusercontent.com/35456349/121790578-1c6e4180-cbe1-11eb-8da2-5a082c2b8b00.png)

Render : 
![image](https://user-images.githubusercontent.com/35456349/121790583-2132f580-cbe1-11eb-9592-4a9a654106a4.png)

Code : 
https://github.com/pierreminiggio/spinning-manager-clip-maker/blob/99926ab862430c895ec8028304460cdf8f5186fa/src/TextSequence.tsx
(Most of my CSS properties come from the props, it can be reproduced using the default props of my project).

**Comment by JonnyBurger** [comment] 2021-06-13 14:21
Hey Pierre!

Although I am able to reproduce it from your repo, this behavior including it's quirks is entirely controlled by the browser engine. Probably it occurs because the preview window is not at 1:1 scale (unless you set the dropdown from "Fit" to "100%").

Unfortunately these browser quirks also apply to Remotion automatically and there is nothing we can do about it. So I have to close it because there is no action on our side that we can take.
If it is a dealbreaker for you, I can recommend writing a ticket on crbug.com and ask them to improve the handling. Sorry!

**Closed by JonnyBurger** 2021-06-13 14:21 UTC

**Comment by pierreminiggio** [comment] 2021-06-13 14:47
No worry, it doesn't bother me. I just though at first that the graphical issue was me sucking at CSS (I still suck at CSS though). :D
