### ISSUE TITLE
OffthreadVideo error when trying to screenshot 0.000ms

### ISSUE THREAD

**Issue by samdoeswork** [remotion-dev/remotion#1342] opened 2022-09-24 13:54 UTC
When using OffthreadVideo this error is raised by FFMPEG
"Invalid duration specification for ss: 0.000ms"

Hopefully it's a simple fix to not take the screenshot if that's the duration, or to automatically replace it with 0.001

**Comment by JonnyBurger** [comment] 2022-09-25 08:27
Hi @samdoeswork!

Thanks a lot for the report, in my version of FFMPEG actually this does not happen (`ffmpeg -ss 0.000ms -i public/framer.webm -frames:v 1 -f image2 -vcodec mjpeg out.png`).

Can you post the output of `ffmpeg -buildconf`? It seems like the last version of FFMPEG that would fail on `0` is from 2011, which seems unlikely but it's good to check!

**Comment by JonnyBurger** [comment] 2022-10-28 15:13
Have to close it because no way I can reproduce it

**Closed by JonnyBurger** 2022-10-28 15:13 UTC
Labels: bug
