### ISSUE TITLE
Pan zooming is disabled at 100%

### ISSUE THREAD

**Issue by wcandillon** [remotion-dev/remotion#2002] opened 2023-04-08 11:13 UTC
When zooming (at 50% for instance), I can nicely pan over my composition with the mouse. However, at 100% no panning seems to be possible. could it be an issue on my side?

**Comment by JonnyBurger** [comment] 2023-04-08 12:38
It is an intended feature - the consideration is that one hand it is easy to accidentially pan away which would disable "Fit" mode, and on the other hand, panning when in "Fit" mode doesn't accomplish much because the whole canvas is already visible.

So the intended user experience is that you first zoom in or out and then panning is enabled.

Closing because it is working as intended, but still open to hear your thoughts!

**Comment by JonnyBurger** [comment] 2023-04-08 12:53
I see, I assumed you meant "Fit". That you cannot zoom at 100% is a bug indeed!

**Closed** 2023-04-10 10:42 UTC
Labels: bug
