### ISSUE TITLE
Remotion is not recognized on windows 

### ISSUE THREAD

**Issue by riungemaina** [remotion-dev/remotion#2831] opened 2023-09-02 09:10 UTC
I am on windows 11, and Node v-18.17.1 and for some reason running `npm start` gives me the error 
```bash
'remotion' is not recognized as an internal or external command, operable program or batch file
```
`npx remotion` also gives the same error. 
I have tried getting a fresh install but that did not fix it.
![Screenshot 2023-09-02 at 12 06 48](https://github.com/remotion-dev/remotion/assets/51113345/95513518-7175-4fc3-9f99-a0f96cb9f071)

**Comment by JonnyBurger** [comment] 2023-09-02 11:44
Is there a folder in this directory `node_modules/@remotion/cli`?

`@remotion/cli` needs to be installed for this to work

**Comment by JonnyBurger** [comment] 2023-09-12 11:49
Sorry, due to not enough information, we need to close the issue.
If you are able to debug the issue with us, comment and we can find the cause and find a solution.

**Closed by JonnyBurger** 2023-09-12 11:49 UTC
Labels: bug
