### ISSUE TITLE
Incomplete rendering of long image

### ISSUE THREAD

**Issue by winner106** [remotion-dev/remotion#3493] opened 2024-02-18 17:10 UTC
Remotion Version: V4.0.114

A problem occurred when I tried to render an image (`width: 1200, height: 18050`). The image could be rendered successfully, but the image was inconsistent with the studio preview.

The studio preview is perfect, but the content displayed in the bottom of the rendered image is actually the top content of the preview, the preview is not fully rendered.

![image](https://github.com/remotion-dev/remotion/assets/50519642/49c8e7d9-b252-4be0-b706-282552b9b9d2)

**Comment by JonnyBurger** [comment] 2024-02-19 11:42
Sounds like a Chrome problem actually. But just to check, can you also post the code to see if it there is something I spot?

**Comment by winner106** [comment] 2024-02-19 15:49
Okay, the code for composition is as follows， thanks.

```tsx
function TableHeaders() {
	const fontSize = 28;
	const headersData = [
		{label: 'id', textAlign: 'left'},
		{label: 'title', textAlign: 'center'},
		{label: 'category', textAlign: 'left'},
	];

	return (
		<Tr border="2px" borderColor="teal" bgColor="teal" height={'80px'}>
			{headersData.map((header, index) => (
				<Th key={index} fontSize={`${fontSize}px`} color="white" textAlign={header.textAlign as any} p={4}>
					{header.label}
				</Th>
			))}
		</Tr>
	);
}

function TableRow({rowData, index, arrLength}: any) {
	const fontSize = 24;
	const contentTypeScale = d3.scaleOrdinal(['article', 'video', 'pic'], ['red', 'orange', 'twitter', 'gray']);
	const customTitleFontSize = {171: 20} as any;
	return (
		<Tr border={'2px'} borderColor="teal.200" width={'100%'} height={'80px'}>
			<Td key={`tr-1`} fontSize={`${fontSize}px`} fontFamily={'body'} width={'1%'} textAlign={'center'}>
				{rowData['id']}
			</Td>

			<Td key={`tr-4`} fontSize={`${customTitleFontSize[index + 1] ?? fontSize}px`} paddingRight={4} width={'74%'} height={'100%'}>
				<Flex width="100%" alignItems={'center'} position={'relative'} height={'100%'}>
					<Box position={'absolute'} width="100%" textAlign={'left'} padding={0} margin={0} color={'gray.700'} fontFamily={'AlibabaBold'}>
						{rowData['title']}
						<Tag
							position={'absolute'}
							marginLeft={1}
							size="lg"
							fontSize="md"
							colorScheme={contentTypeScale(rowData['type'])}
							px={1.5}
							fontFamily={'alibabashuhei'}
						>
							{rowData['type']}
						</Tag>
					</Box>
				</Flex>
			</Td>
			<Td key={`tr-6`} fontSize={`${22}px`} paddingRight={4} height={'100%'}>
				<Flex width="100%" alignItems={'center'} position={'relative'} height={'100%'}>
					<Box position={'absolute'} width="100%" textAlign={'left'}  color={'gray.700'}>
						{rowData['category']}
					</Box>
				</Flex>
			</Td>
		</Tr>
	);
}

export function DataTable() {
	return (
		<>
			<Card p="2%" height="100%" width={'100%'} justifyContent={'center'}>
				<CardHeader>
					<ChartTitle
						borderLeftColor="#d82325"
						outlineColor="#efbf50"
						titleColor="#144579"
						subtitleColor="gray"
						titleFontSize="66"
						subTitleQuery={['']}
						subTitleQueryStyles={{color: '#144579'}}
						subtitleFontSize="40"
						position={'absolute'}
						top={'0.3%'}
						left={'3%'}
					/>
				</CardHeader>

				<CardBody marginTop={'16%'} padding={2} mb="31px" position="relative">
					<TableContainer>
						<Table variant="striped" colorScheme="teal" size={'xl'}>
							<Thead bgColor={'teal'}>
								<TableHeaders />
							</Thead>

							<Tbody color={'#1f2428'}>
								{data.map((item, rowIndex) => {
									return <TableRow key={`TableRow-${rowIndex}`} rowData={{序号: rowIndex + 1, ...item}} index={rowIndex} arrLength={data.length} />;
								})}
							</Tbody>
						</Table>
					</TableContainer>
				</CardBody>
			</Card>
			<WaterMark count={12} opacity={0.1} color={'teal'} zIndex={999999} scale={1.5} />
		</>
	);
}
```

**Comment by winner106** [comment] 2024-02-19 15:57
When I adjusted the height to `16000`, the rendering worked fine, maybe there's a bug when the height reaches some upper limit

**Comment by JonnyBurger** [comment] 2024-02-23 10:47
The code is not in a runnable state for me so I can probably not reproduce this.

I tried the following:

```tsx
export const Framer: React.FC = () => {
	return (
		<div
			style={{
				display: 'flex',
				justifyContent: 'center',
				alignItems: 'center',
				flex: 1,
				height: 18050,
				backgroundImage: 'linear-gradient(to bottom, #000 0%, #ffffff 100%)',
			}}
		/>
	);
};
```

On a 1080x18050 canvas. 

Seems fine actually.

![image](https://github.com/remotion-dev/remotion/assets/1629785/8ac845f0-1b8a-44a8-97ee-22da4f922f54)

I need to close it if there are no further information, because there's nothing I can do to act on it.

**Closed** 2024-02-23 12:59 UTC
Labels: bug
