### ISSUE TITLE
TransitionSeries is not working - Internals.addSequenceStackTraces is not a function 

### ISSUE THREAD

**Issue by hhsadiq** [remotion-dev/remotion#3297] opened 2023-12-24 15:19 UTC
Using the TransitionSeries causing this issue

remotion__WEBPACK_IMPORTED_MODULE_2__.Internals.addSequenceStackTraces is not a function 

./node_modules/@remotion/transitions/dist/TransitionSeries.js
node_modules/@remotion/transitions/dist/TransitionSeries.js:147

 144
TransitionSeries.Sequence = SeriesSequence;
 145
TransitionSeries.Transition = TransitionSeriesTransition;
 146
export { TransitionSeries };
 147
Internals.addSequenceStackTraces(TransitionSeries);
 148
Internals.addSequenceStackTraces(SeriesSequence);
 149

# Bug Report 🐛

Follow the guidelines here https://www.remotion.dev/docs/transitions/transitionseries, copy paste code, and run, should get above error.

**Comment by JonnyBurger** [comment] 2023-12-24 15:55
Sounds like the `remotion` package was not updated like the others. Can you check that?

**Comment by JonnyBurger** [comment] 2023-12-24 16:37
You can update all remotion dependencies to 4.0.81 to resolve the issue! These should always use the same version.

If the issue is resolved, then feel free to close the issue!

**Closed as completed** 2023-12-25 04:06 UTC
Labels: bug
