### ISSUE TITLE
Allow a `toneFrequency` prop to be passed to `<Audio>` (Change pitch of Audio)

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2932] opened 2023-09-26 06:33 UTC
Allow to change the pitch (technically named "tone frequency") of an audio.

## Desired API

`<Audio toneFrequence={0.9} />` 

When calling [`registerRenderAsset()`](https://github.com/remotion-dev/remotion/blob/8fe522de3e06268ed576ac2820c010fb54de8bd3/packages/core/src/audio/AudioForRendering.tsx#L91), this information gets passed and when it arrives at preprocessAudioTrack, then a FFmpeg filter will be applied. 

For example `<Audio toneFrequency={0.9} />` could result in a `asetrate=44100*0.9,aresample=44100,atempo=1/0.9` filter being applied to the audio.

Filter taken from this answer: https://stackoverflow.com/questions/53374590/ffmpeg-change-tone-frequency-keep-length-pitch-audio

## Acceptance criteria

- Should implement a way to change the pitch of the audio during rendering.
- Should prevent changing the pitch over time (we do not need to support this right now)
- Add it to the `<Audio>` docs
- Mention limitations in docs: Must have static value per audio (no change over time), will only work during rendering and not in preview
- Implement min / max values that seem rational to your judgement

## Bounty

💎 This issue is part of Hacktoberfest and has a bounty on it!
- **General Rules**: https://www.remotion.dev/bounties
- **How to contribute**: https://www.remotion.dev/docs/contributing/
- **Implementing a new feature**: https://www.remotion.dev/docs/contributing/feature
- **Implementing a new option**: https://www.remotion.dev/docs/contributing/option
- **Write documentation**: https://www.remotion.dev/docs/contributing/docs

🎃 **Hacktoberfest rules**
- You can only work on 1 issue at a time.
- Only 1 person can work on the same issue.
- We explicitly assign a developer. Don’t work on an issue if we do not assign you.
- First-time contributors will get preferential treatment.
- You must set up the Remotion repository locally and test your changes. [Contributing to Remotion | Remotion | Make videos programmatically in React](https://www.remotion.dev/docs/contributing)
- Your PR must fulfill the acceptance criteria.
- If you use AI, you must verify that the output is correct.
- All tests (functionality and formatting) must pass.

Issue already taken? Find more issues under https://remotion.dev/bounties

/bounty 200

**Comment by evoxf1** [comment] 2023-09-27 09:58
Hello Jonny, IS this issue solve under #2935 , because there you added the asetrate filter in the toml file? or it is still open ?

**Comment by JonnyBurger** [comment] 2023-09-27 10:19
@evoxf1 The issue is not yet solved, adding the necessary FFmpeg dependencies is just the necessary ground work.

**Comment by evoxf1** [comment] 2023-09-27 10:47
oh, well then, what is the actual expected behavior of this, also can I try to work on this issue, I tried to go through the codebase but it might take a while?

**Comment by JonnyBurger** [comment] 2023-10-02 11:51
@evoxf1 I now specified the issue and documented some pointers, and added a cash bounty if you would like to try it!

**Comment by evoxf1** [comment] 2023-10-02 12:18
@JonnyBurger  ok, i am giving it a shot, if not my capability I will soon revert then you can assign it to someone else. Thanks

**Comment by JonnyBurger** [comment] 2023-10-02 12:32
@evoxf1 Super cool! Let's do it like that and if you have questions, you can also ask them 😊

Thanks and good luck!

**Comment by evoxf1** [comment] 2023-10-03 13:02
@JonnyBurger , i didnt find it difficult in the starting ,and now when i figured it out I am facing lot of swirly red lines. PS i am working on it but maybe need some help, :(

**Comment by JonnyBurger** [comment] 2023-10-03 14:51
Ok, first important point: The tone will only shift during rendering! No need to do anything in the component.

The value that you get from the props should be passed to registerRenderAsset() in AudioForRendering.

Pass the value through until you read it out from `preprocessAudioTrack()` https://github.com/remotion-dev/remotion/blob/d8161e47779ca6f32ec2156d2b55e0a09fd68dab/packages/renderer/src/preprocess-audio-track.ts#L1

and then use the above mentioned FFmpeg filter.

You should only hear a difference when you ar rendering a video.

**Comment by evoxf1** [comment] 2023-10-03 16:39
@JonnyBurger  I did some tweaks, can i show u before to avoid unnecessary  PRs.

**Comment by JonnyBurger** [comment] 2023-10-03 16:47
You can open a draft PR nonetheless, and then amend it.

**Comment by evoxf1** [comment] 2023-10-03 17:30
@JonnyBurger  opened a draft PR.

**Comment by JonnyBurger** [comment] 2023-10-03 17:31
Where do you struggle?

**Comment by evoxf1** [comment] 2023-10-04 05:40
@JonnyBurger , i did the desired, but idk about the tests failing, i didnt even changed the formatting !

**Comment by evoxf1** [comment] 2023-10-04 08:53
> Where do you struggle?

@JonnyBurger , i did the desired, but idk about the tests failing, i didnt even changed the formatting !
Should I try again after formatting and linting, I just read your updated contributionn guide if everything seems okay?

**Comment by JonnyBurger** [comment] 2023-10-04 09:04
@evoxf1 Glad you already saw it, indeed we had no guide for this and new we have one: https://www.remotion.dev/docs/contributing/formatting

Use this to make your formatting pass.

Regarding functionality, this is going into the right direction.

Right now you are passing `null` always, you should make it so that the prop actually gets passed through.

Also, no FFmpeg filter is applied. Also implement it and use the contributing guide to test if it works.

**Comment by evoxf1** [comment] 2023-10-04 11:46
@JonnyBurger  creating a PR, the test passed in the local setup as per to the contributing guide, :)
If it failed feel free to assign anyone else as I know I took too much time.

**Comment by JonnyBurger** [comment] 2023-10-04 13:05
@evoxf1 Thanks, the formatting is good and the code is not bad actually!
What is missing is that it actually works, a.k.a. if you add the prop, it doesn't actually influence anything 😄

There is no time rush either. 

Do you feel confident in your ability or do you want me to reassign it to someone else?

**Comment by evoxf1** [comment] 2023-10-04 13:23
Okay i will try again, cant giveup, now the motivation is not bounty.

It doesnt work when we pass the prop. Umm, okay if there is no time bound then i will give it a shot once again. @JonnyBurger

**Comment by evoxf1** [comment] 2023-10-04 13:25
Can we trade the bounty for a pupil?🥲

**Comment by JonnyBurger** [comment] 2023-10-04 13:28
I think too that you can achieve this!

Remove the hardcoded `null` value for toneFrequency, and then keep fixing the TypeScript errors that appear, and you will already be a lot closer.

**Comment by evoxf1** [comment] 2023-10-04 13:33
Is there a discord or slack server of remotion?

**Comment by JonnyBurger** [comment] 2023-10-04 13:39
Yes, https://remotion.dev/discord

you can write in #contributing

**Comment by evoxf1** [comment] 2023-10-05 10:30
@JonnyBurger  I posted a query in the discord server and it is persistant. Thanks

**Comment by JonnyBurger** [comment] 2023-10-05 11:18
Replied!
Note you don't need to close and re-open pull requests. You can just push more commits to your PR.

**Comment by evoxf1** [comment] 2023-10-05 11:29
sorry my bad!

**Comment by evoxf1** [comment] 2023-10-06 07:17
@JonnyBurger , I made some changes now it might work and start accepting the prop

**Closed** 2023-10-07 13:06 UTC
Labels: 🥨  hacktoberfest, 💎 Bounty

**Comment by maxmillionbeatz** [comment] 2024-05-16 00:47
Going back to this. It would be an amazing feature if we could just pass in -af filter chains as strings
<Audio  filters="acompressor=threshold=-30dB:ratio=3:attack=10:release=250,loudnorm=I=-16:LRA=11:TP=-1.5,..." />.

And then in the background it will handle all the tiresome labeling for us 👯‍♀️.

**Comment by JonnyBurger** [comment] 2024-05-16 17:01
That would work but if we are going to add support for it, we can make them props `ratio={3} attack={10}` etc.

By default the Remotion FFmpeg binary includes none of those filters to keep the size down, so to enable them, we'd also have to explicitly include them in the FFmpeg compile.

**Comment by Sajyd** [comment] 2025-09-05 21:15
Would be good to have it in the <Player> preview component so user can play around with pitch before rendering. Is there any way to make this possible ?
