### ISSUE TITLE
CPU utilization high

### ISSUE THREAD

**Issue by iamkhalidbashir** [remotion-dev/remotion#606] opened 2021-09-25 14:52 UTC
# Bug Report 🐛

![Screenshot from 2021-09-25 19-48-52](https://user-images.githubusercontent.com/27646811/134775622-b28b07cc-6002-4110-b54d-d5bd360dc0a8.png)

Before running a render process the CPU utilization is under 1 percent

But after that its around 55% even wehn no render is in process

This happens when I get timeout Error 30000ms which also doesn't stop the render.

**Comment by JonnyBurger** [comment] 2021-09-26 09:22
@iamkhalidbashir Thanks a lot for filing!

I just did some testing and artificially caused a timeout. In neither main branch nor PR #594 a zombie Chrome process was staying after the render failed. So I could not reproduce it.

Can you see a Chrome process remaining in task manager? Are you using normal release or #594 PR?

**Comment by JonnyBurger** [comment] 2022-01-23 12:02
I'm closing this because we cannot take any action based on the provided information.

**Closed by JonnyBurger** 2022-01-23 12:02 UTC
Labels: bug
