### ISSUE TITLE
Audio bounces back when moving the mouse

### ISSUE THREAD

**Issue by reactone** [remotion-dev/remotion#2657] opened 2023-07-31 21:06 UTC
Ive noticed a strange bug when playing audio files. Im using an Audio component and added an audio file from the url. The audio plays fine when Im not moving the mouse over the player, but when I start moving the cursor it tends to go back 100-1000ms and repeat the portion that has already been played. I guess its something with the re-rendering. I was wondering if anybody else experienced this as well and knows what could be the  potential problem and solution?

**Comment by JonnyBurger** [comment] 2023-08-01 14:57
Hi @reactone! We had an unnecessary re-render when you hover over the player. This was fixed in `v4.0.14` (released yesterday). Do you already have this version?

**Comment by JonnyBurger** [comment] 2023-08-07 08:27
I assume so and am closing this issue due to no way for us to reproduce this issue.

**Closed by JonnyBurger** 2023-08-07 08:27 UTC
Labels: bug
