### ISSUE TITLE
Random ENOENT failure with complex-filter file

### ISSUE THREAD

**Issue by akx** [remotion-dev/remotion#1653] opened 2023-01-09 06:37 UTC
# Bug Report 🐛

Randomly, the `complex-filter` file has disappeared before `ffmpeg` is run.
Restarting the job (and re-rendering all 1100 frames 😪) helps.

```
$ remotion render Foo ./out/foo.mp4 --crf 19 --image-format png --scale 0.5 --concurrency 4 --props '{"redacted": true}'
(1/3) [====================] Bundled code 955ms
Entry point = src/index.ts (common paths), Composition = Foo (Passed as argument), Codec = h264 (derived from out name), Output = ./out/foo.mp4
(2/3) [====================] Rendered frames (4x) 615425ms
    + [====================] Downloading http://localhost:3002/public/music.mp3
(3/3) [                    ] Encoding video 0/1100
An error occurred:
Error: ENOENT: no such file or directory, open '/var/folders/n0/8r8c6bms2fj7753rvhmtybqm0000gn/T/remotion-v3-3-27-assetszwb2b3dcjd/remotion-complex-filter/complex-filter-05051967092679592.txt'
```

**Comment by JonnyBurger** [comment] 2023-01-09 14:28
I was not able to find a location in the code where the directory could be prematurely deleted.

A cause could be an external program trying to clean the temporary directory from time to time. Do you have any tools like MacKeeper, CCleaner etc. set up that would try to do this? Is this a plausible explanation?

**Comment by JonnyBurger** [comment] 2023-01-17 16:46
I have to close it because there is no way to reproduce and find something out about this problem, making it an inactionable issue unfortunately.

**Comment by preetparm** [comment] 2023-03-31 22:15
Got the same kind of error
Encoding video 38730/38730 
An error occurred:
Error: ENOENT: no such file or directory, open 'C:\Users\PARAMP~1\AppData\Local\Temp\remotion-v3-3-79-assetsy98s167mci\remotion-complex-filter\complex-filter-042497056491388174.txt'

**Comment by JonnyBurger** [comment] 2023-04-03 14:47
Okay, adding an additional check that if temp dir is being cleaned, we regenerate the folder. Although original problem is unknown, this should at least not crash anymore 🙏

**Closed** 2023-04-03 15:17 UTC
Labels: bug

**Comment by preetparm** [comment] 2023-04-03 15:24
Thanks @JonnyBurger  for fixing the issue and providing brilliant  video editor .
