### ISSUE TITLE
Audio not working when using the loop prop

### ISSUE THREAD

**Issue by matt-sanders** [remotion-dev/remotion#2188] opened 2023-05-04 23:13 UTC
# Bug Report 🐛

We have come across a strange issue when using the `loop` property of the `Audio` component within a `Sequence`. We have a particular audio file that will not play given the following conditions:
- it is within a `Sequence` component with the `from` prop set to `0` or `undefined`
- `loop` is set to `true`
- the `durationInFrames` of the `Player` component is set less than or equal to `6035`. Anything above that works.

For some context, we have a component which renders the `Sequence` with a conditional `from` and `durationInFrames`. We pass this component some props so that it can calculate when certain elements should be added / removed from the composition. A minimal example is this:
```jsx
function OurSequenceComponent({ children, ...props }) {
  const from = calculateFrom(props)
  const durationInFrames = calculateDuration(props)
  return (
    <Sequence from={from} durationInFrames={durationInFrames}>
      {children}
     </Sequence>
  )
}
```

As part of that we end up rendering the `Audio` component inside a `Sequence` component. Sometimes this `Sequence` plays from the beginning of the components, hence receiving `0` as its `from` prop. We were noticing that the audio would sometimes play and sometimes not, and this led us to discover the issue. The `durationInFrames` seems to have a relationship with the duration of the audio file. Other files with a different duration run under the same conditions seem to play fine.

I initially tried to remove the `Sequence` when `from === 0` but this became problematic because we also needed to pass in a `durationInFrames`. It appeared to me that `from` needed to be greater than 0 for it to work.

If there are steps we can take to solve this issue our end I'd love to hear them, but it appears like this may be a bug within remotion.

[Here's a codesandbox](https://codesandbox.io/s/remotion-audio-loop-issue-4hpu3i?file=/src/App.js) that reproduces the issue. Let me know if you need any more detail.

**Comment by JonnyBurger** [comment] 2023-05-05 08:30
Thanks a lot for providing this great reproduction!
I've been able to track a bug down due to this and it will be fixed in the next release!

**Closed** 2023-05-05 12:22 UTC
Labels: bug
