### ISSUE TITLE
Remotion player is not working in 4.0.63

### ISSUE THREAD

**Issue by kiyosoft** [remotion-dev/remotion#3132] opened 2023-11-07 07:54 UTC
Remotion player is not rendering in the latest version

# Bug Report 🐛

I have created a new remotion project with next js starter with the latest version(4.0.64) of remotion, but unfortunately the player doesn't render the video and when I downgrade it to `4.0.48` not it starts working

**Comment by JonnyBurger** [comment] 2023-11-07 07:55
Thanks for reporting! This will be fixed in v4.0.65.

The cause was a Turborepo upgrade which somehow led to an old version of Remotion be re-published again.

**Closed by JonnyBurger** 2023-11-07 07:55 UTC
Labels: bug
