### ISSUE TITLE
Node 20 Tailwind issue

### ISSUE THREAD

**Issue by JonnyBurger** [remotion-dev/remotion#2972] opened 2023-10-04 12:07 UTC
node 20.8.0
npm 10.1.0

npm init video --> Tailwind

![image](https://github.com/remotion-dev/remotion/assets/1629785/e37650b3-e019-423a-8c01-d43140cc31ba)

Context issue?

Reported by RATCHAW

**Comment by patsalv** [comment] 2023-10-04 14:45
Could not reproduce this behavior, closing it for now.

**Closed by patsalv** 2023-10-04 14:45 UTC
