### ISSUE TITLE
Problem with measureText (from canvas) using other font than Times

### ISSUE THREAD

**Issue by JesperHalvorsen** [remotion-dev/remotion#853] opened 2022-02-26 19:28 UTC
When using svg texts, I have to do a number of calculations to get size of texts (height & width). Using code like this works fine in the preview/player:

```js
export function getTextHeight(text: string, font?: string) {
	const canvas = document.createElement('canvas');
	const context = canvas.getContext('2d');

	context!.font = font || getComputedStyle(document.body).font;

	return context!.measureText(text).actualBoundingBoxAscent + context!.measureText(text).actualBoundingBoxDescent;
}
```

But when I render stills/videos using the CLI, there is a problem with the first frame: size returned is not correct - from what I can figure out, the font being used is Times, not the fontFamily I specify (and I believe that the default Chromium font is Times).

For me, it seems like the loading of the font has not completed when the first frame is rendered, but works fine for the rest of the frames.

For video, it's not a big problem, as I can just render the text opaque in the first frame, but for stills, there is only one frame 😊

I've attached a screenshot of a still component in the preview and the output from the CLI (where the texts have been clipped):

![cli](https://user-images.githubusercontent.com/38975532/155856356-84f9b02e-ccc6-4758-9e57-32ebab965fd7.jpg)
![player](https://user-images.githubusercontent.com/38975532/155856357-b6cfcb47-5bc5-465a-8898-91c032cedb90.png)

**Comment by JesperHalvorsen** [comment] 2022-02-26 19:34
Forgot to add, that the font paramenter for context.fort is something like "bold 100px SomeFancyFont"

(https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/font)

**Comment by JonnyBurger** [comment] 2022-02-27 09:14
Hi Jesper!

Since the fonts are loaded asynchronously, you will need to wait until the fonts are loaded until you can measure the text. Try using the `document.fonts.ready` API:

```ts
document.fonts.ready.then(() => {/* now measure the text */})
```

or the `document.fonts.check()` API:

```ts
const prom = new Promise((resolve) => {
	const check = () => {
		if (document.fonts.check('1em Rubik')) {
			resolve()		
		} else {
			setTimeout(check, 100)
		}
	}
});

prom.then(() => { /* Now measure the text */ })
```

You can also tell Remotion to wait for the fonts to be loaded before it should render: Call `delayRender()` at the beginning, and `continueRender()` when the fonts have been loaded. See: https://www.remotion.dev/docs/delay-render

**Comment by JesperHalvorsen** [comment] 2022-02-27 10:10
Hi Jonny

First of all: thanks for the very quick reply. I did try using delayRender() like this:

```
import './fonts.scss'

export const ColorFilterComposition: React.FC<{
	photo: string,
	texts: Array<string>,
	margin?: number,
	lineHeight?: number,
	fontName?: string,
	fontWeight?: string,
	fontColor?: string,
	fontSize?: number,
	filterColor?: string,
	rightAlign?: boolean,
}> = ({ photo, texts, margin = 10, lineHeight = 14, fontName = 'times', fontSize = 100,
	fontColor = 'white', fontWeight = 'normal', filterColor = 'red', rightAlign = false }) => {

		const [handle] = useState(() => delayRender());
		const { width } = useVideoConfig();

		const [textSizes, setTextSizes] = useState<any>([]);
		const [maxWidth, setMaxWidth] = useState(0);

		useEffect(() => {
			const tmpTextSizes = texts.map((t) => getTextSize(t, `${fontWeight} ${fontSize}px ${fontName}`));
			setTextSizes(tmpTextSizes);

			const tmpMaxWidth = Math.max.apply(Math, tmpTextSizes.map(function(o) { return o.width; }));
			setMaxWidth(tmpMaxWidth);

			continueRender(handle);
		}, []);

		const left = (width * (1 - ((margin - 3) / 100))) - maxWidth;

		if (textSizes.length == 0) {
			return <></>
		}

		return <AbsoluteFill>
			<MonotoneImage photo={photo} filterColor={filterColor} margin={margin} />
			<svg style={{
				position: 'absolute', bottom: `${margin - 3}%`, left: `${left}px`,
				width: `${maxWidth}px`, height: `${(textSizes.reduce((a: any, b: any) => a + b.height, 0)) + (texts.length * lineHeight)}px`, border: '0px solid green'}}>
				{texts.map((t, i) => <g key={i}>
					<text fontSize={fontSize} fontFamily={fontName} fill={fontColor} fontWeight={fontWeight}
						y={textSizes.slice(0, i + 1).reduce((a: any, b: any) => a + b.height, 0) + (i * lineHeight)}
						x={rightAlign ? maxWidth - textSizes[i].width : 0}
						style={{ filter: 'drop-shadow(3px 7px 3px #111111)' }}
					>{t}</text>
				</g>)}
			</svg>
		</AbsoluteFill>
	}
```

But I did get the same result. I'll try to use the fonts.ready solution, and then update the status of the issue.

**Comment by JonnyBurger** [comment] 2022-02-27 10:34
Hi Jesper,

it's good that you are waiting for the font measurement to be done. Remotion also waits for the fonts to be loaded itself automatically. From what it looks like to, what would be appropriate in this case is to 1. wait for the fonts to be loaded 2. **then** measure the text, 3. then call continueRender.

**Comment by JonnyBurger** [comment] 2022-03-01 12:36
Closing the issue because I think the question is answered. In case of doubts, just ask!

**Closed by JonnyBurger** 2022-03-01 12:36 UTC
Labels: bug

**Comment by JesperHalvorsen** [comment] 2022-03-02 18:31
No need to update the status of the issue @JonnyBurger [JonnyBurger](https://github.com/JonnyBurger), just some details that might help others:

I think the issue here is some kind of "optimization". When I ```return <></>``` on first render, the font is never loaded (this is the only component in the composition), because Chrome figuresout, that there is no use for it. And Remotion waits for the document.fonts API to return loaded, which it does.

The second time the component is rendered, as result of the continueRender, Chome figures out it needs to load the font, but this time, Remotion is not waiting/listening to the loaded event. So when I measure, it's the wrong font - the correct font is being loaded.

So just returning a dummy ```<div style={{ fontFamily: 'Rubik' }}>&nbsp;</div>``` the first time, solved the issue for me, and CLI rendering of stills now works fine.

**Comment by JonnyBurger** [comment] 2022-03-05 10:37
@JesperHalvorsen Glad to hear the issue is resolved! That makes sense that the render is cleared when the font is not rendered indeed. Good catch! You could use the `document.fonts.check()` method I gave an example of above to figure out explicitly once a font is done rendering without needing a dummy element.

In any case, glad you got unblocked!
