### ISSUE TITLE
Bun Support

### ISSUE THREAD

**Issue by JLarky** [remotion-dev/remotion#50] opened 2021-02-11 04:03 UTC
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%240%20Funded-%2300A156.svg" />](https://issuehunt.io/r/remotion-dev/remotion/issues/50)

Asking for Deno support is new "asking for typescript support". So I've done it.

```
deno eval 'import * as x from "https://dev.jspm.io/remotion"; console.log(x)'
```

example of the expected result:

```
$ deno eval 'import * as x from "https://dev.jspm.io/lodash"; console.log(x)'
Module { default: [Function: lodash], [Symbol(Symbol.toStringTag)]: "Module" }
```

actual result:
```
$ deno eval 'import * as x from "https://dev.jspm.io/remotion"; console.log(x)'
error: Uncaught TypeError: Cannot read property 'ReactCurrentDispatcher' of undefined
      var ReactCurrentDispatcher = ReactSharedInternals.ReactCurrentDispatcher;
                                                        ^
    at https://dev.jspm.io/npm:react@17.0.1/cjs/react-jsx-runtime.development.dew.js:323:57
    at dew (https://dev.jspm.io/npm:react@17.0.1/cjs/react-jsx-runtime.development.dew.js:1196:7)
    at dew (https://dev.jspm.io/npm:react@17.0.1/jsx-runtime.dew.js:8:15)
    at dew (https://dev.jspm.io/npm:remotion@1.1.1/dist/AbsoluteFill.dew.js:13:25)
    at dew (https://dev.jspm.io/npm:remotion@1.1.1/dist/index.dew.js:51:16)
    at https://dev.jspm.io/remotion:2:16
```

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/remotion-dev/remotion/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
</details>

**Comment by JonnyBurger** [comment] 2021-02-11 17:13
Haha, true that!

I have no experience with Deno, but it is super cool. Realistically, it is probably not the top priority for me personally, other more important features are, but if someone wants to pick it up we can consider it!

**Comment by yuta0801** [comment] 2021-02-12 21:09
It seems to be an issue with dev.jspm.io, it can import successfully with jspm.dev which is the new replacement for dev.jspm.io.

```
$ deno eval 'import * as x from "https://jspm.dev/remotion"; console.log(x)'
Module {
  AbsoluteFill: [Function: AbsoluteFill],
  Audio: [Function: Audio],
  Composition: [Function: Composition],
  ....
  [Symbol(Symbol.toStringTag)]: "Module"
}
```

**Comment by JLarky** [comment] 2021-02-13 02:20
@yuta0801 thanks! but this is just one step on the way there :) I created this issue for general Deno support :) but just to continue playing into Deno whack-a-mole I have this:

```
$ deno eval 'import * as x from "https://jspm.dev/@remotion/renderer"; console.log(x)'
error: Uncaught TypeError: The "original" argument must be of type Function
```

**Comment by JonnyBurger** [comment] 2021-04-25 13:45
Added a bounty to whoever can demonstrate Remotion working on Deno!

I don't know how hard it is or what needs to be changed. This is a low priority issue for me, so putting out a small incentive.

**Comment by rafaelramalho19** [comment] 2021-12-01 03:10
Currently there's no way to allow Deno support while still using typescript (More info here: https://github.com/microsoft/TypeScript/issues/37582) 

Basically, you cannot have something like:

```
import {AnyComponent} from './any-component.ts';
```

Because the TS compiler will just throw: `An import path cannot end with a '.ts' extension. Consider importing './any-component' instead.ts(2691` and deno requires the import to specify the file extension.

This is a long going discussion with the TS core team and I don't think they're gonna change any time soon.

One solution would just to migrate totally from typescript to deno. I'm up for this, what you think about it @JonnyBurger ?

**Comment by JonnyBurger** [comment] 2021-12-04 11:46
I think a complete migration to only Deno is out of the question, with Node being the much bigger platform.

If it is sure that it's not possible to support Node and Deno at the same time with one codebase, I would close this issue as the effort to support Deno is too much. Personally I haven't invested time into it yet, and the priority is rather low, although I see it as a nice feature.

**Comment by JonnyBurger** [comment] 2022-06-29 07:17
Some thoughts:

- We can get closer to Deno support by removing as many npm dependencies as possible and inlining them into Remotion. This makes it easier to replace calls to native Node.JS modules (path, os, child_process etc.)
- Besides Deno, there's also https://bun.sh/ which I also find very promising. So it's not just about supporting one more runtime, but being runtime-agnostic possibly.

**Comment by JonnyBurger** [comment] 2022-07-07 06:10
Remotion does not currently run on Bun at the moment at least because of `child_process`.

I'm continuing to eliminate dependencies and try to avoid runtime-specific APIs so when the new JS runtimes mature, we are ready!

**Comment by tomByrer** [comment] 2022-07-24 05:10
> This is a long going discussion with the TS core team and I don't think they're gonna change any time soon.
> 
> One solution would just to migrate totally from typescript to deno.

Which is odd, since one of Deno's earliest goals was to have built-in TS support, so to be Deno-compat is to drop TS is... bad DX.   & improved DX is the only reason to support Deno IMHO, because it is not performance AFAIK.

Bun on the other hand, has both improved DX & better performance for short-lived processes.

Either way, once some of the Node-specific calls are handled directly by Remotion, codemods/monkey-patching might be worth exploring, instead of rewriting.

**Comment by ndren** [comment] 2022-11-14 16:19
I've hacked around and it looks like human-signals is a hurdle. I think updating it to version 3 would resolve the problem though. I got this far (not there yet, but a start!):
`deno eval 'import * as x from "https://jspm.dev/@remotion/renderer"; console.log(x)'`
```
Module {
  ErrorWithStackFrame: [Function: ErrorWithStackFrame],
  RenderInternals: {
    ensureLocalBrowser: [AsyncFunction: ensureLocalBrowser],
    ffmpegHasFeature: [AsyncFunction: ffmpegHasFeature],
    getActualConcurrency: [Function: getActualConcurrency],
    validateFfmpeg: [AsyncFunction: validateFfmpeg],
    serveStatic: [AsyncFunction: serveStatic],
    validateEvenDimensionsWithCodec: [Function: validateEvenDimensionsWithCodec],
    getFileExtensionFromCodec: [Function: getFileExtensionFromCodec],
    tmpDir: [Function: tmpDir],
    deleteDirectory: [AsyncFunction: deleteDirectory],
    isServeUrl: [Function: isServeUrl],
    ensureOutputDirectory: [Function: ensureOutputDirectory],
    getRealFrameRange: [Function: getRealFrameRange],
    validatePuppeteerTimeout: [Function: validatePuppeteerTimeout],
    downloadFile: [Function: downloadFile],
    killAllBrowsers: [AsyncFunction: killAllBrowsers],
    parseStack: [Function: parseStack],
    symbolicateError: [AsyncFunction: symbolicateError],
    SymbolicateableError: [Function: SymbolicateableError],
    getFramesToRender: [Function: getFramesToRender],
    getExtensionOfFilename: [Function: getExtensionOfFilename],
    getDesiredPort: [Function: getDesiredPort],
    isPathInside: [Function: isPathInside],
    execa: [Function: execa] { sync: [Function], command: [Function], commandSync: [Function], node: [Function] },
    registerErrorSymbolicationLock: [Function: registerErrorSymbolicationLock],
    unlockErrorSymbolicationLock: [Function: unlockErrorSymbolicationLock],
    canUseParallelEncoding: [Function: canUseParallelEncoding],
    mimeContentType: [Function: mimeContentType],
    mimeLookup: [Function: mimeLookup],
    validateConcurrency: [Function: validateConcurrency],
    validPixelFormats: [
      "yuv420p",
      "yuva420p",
      "yuv422p",
      "yuv444p",
      "yuv420p10le",
      "yuv422p10le",
      "yuv444p10le",
      "yuva444p10le"
    ],
    DEFAULT_BROWSER: "chrome",
    validateFrameRange: [Function: validateFrameRange],
    DEFAULT_OPENGL_RENDERER: null,
    validateOpenGlRenderer: [Function: validateOpenGlRenderer],
    validImageFormats: [ "png", "jpeg", "none" ],
    validCodecs: [
      "h264",     "h265",
      "vp8",      "vp9",
      "mp3",      "aac",
      "wav",      "prores",
      "h264-mkv", "gif"
    ],
    DEFAULT_PIXEL_FORMAT: "yuv420p",
    validateQuality: [Function: validateQuality],
    validateFrame: [Function: validateFrame],
    DEFAULT_TIMEOUT: 30000,
    DEFAULT_CODEC: "h264",
    isAudioCodec: [Function: isAudioCodec],
    logLevels: [ "verbose", "info", "warn", "error" ],
    isEqualOrBelowLogLevel: [Function: isEqualOrBelowLogLevel],
    isValidLogLevel: [Function: isValidLogLevel],
    perf: {
      startPerfMeasure: [Function: startPerfMeasure],
      stopPerfMeasure: [Function: stopPerfMeasure],
      logPerf: [Function: logPerf]
    },
    makeDownloadMap: [Function: makeDownloadMap],
    cleanDownloadMap: [AsyncFunction: cleanDownloadMap],
    convertToPositiveFrameIndex: [Function: convertToPositiveFrameIndex],
    validateBitrate: [Function: validateBitrate],
    getFfmpegVersion: [AsyncFunction: getFfmpegVersion]
  },
  __esModule: true,
  combineVideos: [AsyncFunction: combineVideos],
  default: {
    combineVideos: [Getter],
    ErrorWithStackFrame: [Getter],
    getCompositions: [Getter],
    validateSelectedPixelFormatAndImageFormatCombination: [Getter],
    validImageFormats: [Getter],
    makeCancelSignal: [Getter],
    openBrowser: [Getter],
    renderFrames: [Getter],
    renderMedia: [Getter],
    renderStill: [Getter],
    stitchFramesToVideo: [Getter],
    validateOutputFilename: [Getter],
    RenderInternals: {
      ensureLocalBrowser: [AsyncFunction: ensureLocalBrowser],
      ffmpegHasFeature: [AsyncFunction: ffmpegHasFeature],
      getActualConcurrency: [Function: getActualConcurrency],
      validateFfmpeg: [AsyncFunction: validateFfmpeg],
      serveStatic: [AsyncFunction: serveStatic],
      validateEvenDimensionsWithCodec: [Function: validateEvenDimensionsWithCodec],
      getFileExtensionFromCodec: [Function: getFileExtensionFromCodec],
      tmpDir: [Function: tmpDir],
      deleteDirectory: [AsyncFunction: deleteDirectory],
      isServeUrl: [Function: isServeUrl],
      ensureOutputDirectory: [Function: ensureOutputDirectory],
      getRealFrameRange: [Function: getRealFrameRange],
      validatePuppeteerTimeout: [Function: validatePuppeteerTimeout],
      downloadFile: [Function: downloadFile],
      killAllBrowsers: [AsyncFunction: killAllBrowsers],
      parseStack: [Function: parseStack],
      symbolicateError: [AsyncFunction: symbolicateError],
      SymbolicateableError: [Function: SymbolicateableError],
      getFramesToRender: [Function: getFramesToRender],
      getExtensionOfFilename: [Function: getExtensionOfFilename],
      getDesiredPort: [Function: getDesiredPort],
      isPathInside: [Function: isPathInside],
      execa: [Function: execa] {
        sync: [Function],
        command: [Function],
        commandSync: [Function],
        node: [Function]
      },
      registerErrorSymbolicationLock: [Function: registerErrorSymbolicationLock],
      unlockErrorSymbolicationLock: [Function: unlockErrorSymbolicationLock],
      canUseParallelEncoding: [Function: canUseParallelEncoding],
      mimeContentType: [Function: mimeContentType],
      mimeLookup: [Function: mimeLookup],
      validateConcurrency: [Function: validateConcurrency],
      validPixelFormats: [
        "yuv420p",
        "yuva420p",
        "yuv422p",
        "yuv444p",
        "yuv420p10le",
        "yuv422p10le",
        "yuv444p10le",
        "yuva444p10le"
      ],
      DEFAULT_BROWSER: "chrome",
      validateFrameRange: [Function: validateFrameRange],
      DEFAULT_OPENGL_RENDERER: null,
      validateOpenGlRenderer: [Function: validateOpenGlRenderer],
      validImageFormats: [ "png", "jpeg", "none" ],
      validCodecs: [
        "h264",     "h265",
        "vp8",      "vp9",
        "mp3",      "aac",
        "wav",      "prores",
        "h264-mkv", "gif"
      ],
      DEFAULT_PIXEL_FORMAT: "yuv420p",
      validateQuality: [Function: validateQuality],
      validateFrame: [Function: validateFrame],
      DEFAULT_TIMEOUT: 30000,
      DEFAULT_CODEC: "h264",
      isAudioCodec: [Function: isAudioCodec],
      logLevels: [ "verbose", "info", "warn", "error" ],
      isEqualOrBelowLogLevel: [Function: isEqualOrBelowLogLevel],
      isValidLogLevel: [Function: isValidLogLevel],
      perf: {
        startPerfMeasure: [Function: startPerfMeasure],
        stopPerfMeasure: [Function: stopPerfMeasure],
        logPerf: [Function: logPerf]
      },
      makeDownloadMap: [Function: makeDownloadMap],
      cleanDownloadMap: [AsyncFunction: cleanDownloadMap],
      convertToPositiveFrameIndex: [Function: convertToPositiveFrameIndex],
      validateBitrate: [Function: validateBitrate],
      getFfmpegVersion: [AsyncFunction: getFfmpegVersion]
    }
  },
  getCompositions: [AsyncFunction: getCompositions],
  makeCancelSignal: [Function: makeCancelSignal],
  openBrowser: [AsyncFunction: openBrowser],
  renderFrames: [Function: renderFrames],
  renderMedia: [Function: renderMedia],
  renderStill: [Function: renderStill],
  stitchFramesToVideo: [AsyncFunction: stitchFramesToVideo],
  validImageFormats: [ "png", "jpeg", "none" ],
  validateOutputFilename: [Function: validateOutputFilename],
  validateSelectedPixelFormatAndImageFormatCombination: [Function: validateSelectedPixelFormatAndImageFormatCombination]
}
```
The way I was able to do this is by removing the code that won't run in human-signals forcefully. To reproduce:
```bash
deno eval 'import * as x from "https://jspm.dev/@remotion/renderer"; console.log(x)' # Crash
cp 40b93ab56b85efc2352b611ed158d81be50f4235bcd005ba64f9c56115ffaee2.txt ~/.cache/deno/deps/https/jspm.dev/40b93ab56b85efc2352b611ed158d81be50f4235bcd005ba64f9c56115ffaee2
deno eval 'import * as x from "https://jspm.dev/@remotion/renderer"; console.log(x)' # Success!
```
File to copy: [40b93ab56b85efc2352b611ed158d81be50f4235bcd005ba64f9c56115ffaee2.txt](https://github.com/remotion-dev/remotion/files/10004794/40b93ab56b85efc2352b611ed158d81be50f4235bcd005ba64f9c56115ffaee2.txt)

@JonnyBurger is that bounty still on? :)

**Comment by JonnyBurger** [comment] 2022-11-14 16:22
@ndren Very nice! It certainly is, if it is hard, we are even willing to increase! 

`human-signals` seems to be a dependency of `execa`, maybe it has to be abstracted to not rely on child_process, since this is a Node.JS only module, right?

**Comment by ndren** [comment] 2022-11-14 16:30
@JonnyBurger Maybe? It looks like deno handles it fine:
```
import {execa} from 'npm:execa';
const {stdout} = await execa('id');
console.log(stdout);
```

`deno run test.ts` works as expected. So the issue does not look like it has to do with spawning processes by itself.

**Comment by JonnyBurger** [comment] 2022-11-15 10:10
I see, `require("os").constants` does not work in Deno.

How does that work in Deno? Can it be patched or does the module need to be replaced?

**Comment by ndren** [comment] 2022-11-15 16:52
The following works for me: (`deno run demo.js`)
```
import * as os from "https://deno.land/std@0.42.0/node/os.ts";
console.log(os.constants)
```

**Comment by JonnyBurger** [comment] 2022-11-16 10:18
I see, we could inline that, but how could we make that import so it works on both Node and Deno?

I did a quick test myself:

```ts
import {cli} from 'npm:@remotion/cli';

cli();
```

and tried to run it with

```bash
deno run --allow-read --allow-env --allow-sys --allow-run --allow-write --allow-net src/deno.ts preview src/index.ts
```

and I got the following:

```
Updated env file /Users/jonathanburger/remotion/packages/example/.env
Updated env file /Users/jonathanburger/remotion/packages/example/.env
Updated env file /Users/jonathanburger/remotion/packages/example/.env
Updated env file /Users/jonathanburger/remotion/packages/example/.env

An error occurred:
Error: No available ports found
    at getPort (file:///Users/jonathanburger/Library/Caches/deno/npm/registry.npmjs.org/@remotion/renderer/3.3.0/dist/get-port.js:36:11)
    at async getDesiredPortUnlimited (file:///Users/jonathanburger/Library/Caches/deno/npm/registry.npmjs.org/@remotion/renderer/3.3.0/dist/get-port.js:43:24)
```

So it seems like there are two more problems, `fs.watchFile` being implemented differently, and the `net` module working differently than in Node. We have to get over those differences as well.

**Comment by JonnyBurger** [comment] 2022-11-16 10:22
Latest update on Bun - child_process support is supposed to be coming soon, once it gets released, I'll give it a try as well.

**Comment by ndren** [comment] 2022-11-23 07:54
A bit hacky, but I suppose you always have this:
`navigator.userAgent.substring(0,4) == "Deno"`

**Comment by JonnyBurger** [comment] 2022-11-28 10:47
@ndren But we cannot use this for `import` statements, very clunky. We need a clean solution

**Comment by JLarky** [comment] 2022-11-28 21:22
> A bit hacky, but I suppose you always have this:
> `navigator.userAgent.substring(0,4) == "Deno"`

I'm pretty sure you just do `typeof Deno` :)

**Comment by MehmetAdemi** [comment] 2022-12-08 09:35
Hi there, we removed the bounty because it came out that implementing this feature is more complex than we initially thought. We don’t expect a contributor to implement it. Nevertheless, any help is appreciated. We will put the bounty on another issue.

**Comment by JonnyBurger** [comment] 2023-08-08 13:44
I'm occasionally checking Bun support, the current blocker is support for `fs.watchFile`. But Bun is looking promising!

**Comment by JonnyBurger** [comment] 2023-08-25 09:10
Some progress towards Bun support is achieved, current blocker is https://github.com/oven-sh/bun/issues/4316

**Comment by JonnyBurger** [comment] 2023-08-25 09:11
We don't plan on supporting Deno. In our opinion, the benefits over Node are only minor so that it is not worth the effort to us.

**Comment by MehmetAdemi** [comment] 2023-09-23 09:54
Initially, this issue was meant to support Bun as a runtime. Currently, we support it as a package manager. 
We are working on supporting Bun as a runtime. See [https://remotion.dev/bun](https://t.co/4yCAg6wg1M) for an overview.

**Comment by JonnyBurger** [comment] 2023-09-23 10:41
With Bun 1.0.3, at least issues 2 + 3 seem to be resolved!

<img width="896" alt="image" src="https://github.com/remotion-dev/remotion/assets/1629785/dd31f541-7c8b-4680-bc22-c5a7655c0b58">

Will test 1 + 4 too and then we can indeed call Bun supported :)

**Comment by thecmdrunner** [comment] 2023-09-23 10:58
> then we can indeed call Bun supported :)

Hopefully won't break again after Bun 1.1 🤞

**Comment by JonnyBurger** [comment] 2023-09-25 15:19
Bun is now mostly supported with minor limitations. Those live under https://remotion.dev/bun.

As mentioned before, regarding the original issue title, we have no plans supporting Deno.

**Closed** 2023-09-25 15:55 UTC
