### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by brandonpearcy** [remotion-dev/remotion#479] opened 2021-06-23 16:01 UTC
We just started using Remotion in server mode (e.g. via server.tsx in a Google Cloud Run instance), and noticed that it leaks memory on every render task. 

The two peaks in the chart below show out-of-memory crashes (the memory cap is 4 GB). The third plateau shows that we almost crashed a third time, but the render tasks stop. Eventually the instance was cleaned up, so the data ends. Not sure if it is helpful, but this chart represents 242 render tasks, each of which is rendering a single PNG (we're not stitching together videos at this point). Each render tasks downloads three unique images from a CDN. 

<img width="202" alt="Screen Shot 2021-06-23 at 8 52 27 AM" src="https://user-images.githubusercontent.com/17098317/123128875-5a007500-d400-11eb-8492-33d2db76a83d.png">

- Since we're downloading assets for every render task, is there any manual cleanup required between tasks?
- Any hunches as to what could be causing the leakage?
- Any tips for debugging memory utilization / leaks?

Huge thanks in advance for any help that can be provided, and I'm happy to contribute back to the Remotion "Troubleshooting" documentation afterwards.

**Comment by JonnyBurger** [comment] 2021-06-23 20:18
Thanks for filing the issue! Together with #479, I believe there is indeed an issue, and I'll investigate it later this week. 

Will keep you updated here.

**Comment by brandonpearcy** [comment] 2021-06-23 21:18
I *think* you meant to link to #442 , but just guessing!

**Comment by JonnyBurger** [comment] 2021-06-24 07:11
Yes you are right! Sorry and thanks for linking it now.
Maybe it's not the same since you are stitching it together.

I just tried a memory profile (used the following script if you want to compare: https://gist.github.com/JonnyBurger/1b51dd3513ae311e24cd0fa4f90580b0 - it's not necessary to bundle in every loop, but I tried to see if that would cause a problem)

and after 100 iterations, the memory stayed low (200-300MB) always.
From first sight, I don't see a memory leak. If you don't download the images (let's say you always use the same ones), does the problem go away?

Are you calling any other Remotion APIs directly other than `bundle`, `getCompositions` and `renderFrames`?

If you are willing to let me peek into the render code, you can also message me privately e.g. on Discord and I will take a look as well if I can reproduce it.

**Comment by brandonpearcy** [comment] 2021-06-24 17:03
Thanks for the suggestions. I did a little experimentation, and was able to quickly narrow down where the memory leak is. I don't know the exact cause of it, but I'd say the memory leak is in `getCompositions`. 

Is it possible that `getCompositions` is spinning up a new browser instance on each render task without cleaning up the old ones?

✅ We are bundling once as part of our deployment process, so it's not that.

✅  Removing call to `getCompositions` and using the same assets in every render task  => no increase in memory utilization over time.
<img width="653" alt="Screen Shot 2021-06-24 at 9 17 30 AM" src="https://user-images.githubusercontent.com/17098317/123298093-03ad3800-d4cd-11eb-84f8-e17a13299d22.png">

❌  Calling `getCompositions` and using the same assets in every render task  => fast increase in memory utilization
<img width="719" alt="Screen Shot 2021-06-24 at 9 50 32 AM" src="https://user-images.githubusercontent.com/17098317/123302512-9f40a780-d4d1-11eb-8f3b-825522d1d7fa.png">

Aside: When I was first getting started with Remotion, I was tempted to bypass `getCompositions` because our composition configs are static: always the same width, height, FPS, and duration. Do you agree it would be best to just replace the call to `getCompositions` with a composition ID => configuration map? Or are there other good reasons to call `getCompositions`?

**Comment by JonnyBurger** [comment] 2021-06-24 17:55
Yes you are right! Thanks for tracking that down 🙌 

I merged a fix and released a new version: `v2.1.12`. Now the browser gets closed after calling getCompositions().

By the way, yes it's sensible to not call it at all, or at least don't call it more than once (same with `bundle()`). It'll work just as fine!

**Closed by JonnyBurger** 2021-06-24 17:55 UTC
